---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: portworx-sc-med-io
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
  priority_io: "medium"
allowVolumeExpansion: true