apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypted-pvc-pod
  namespace: portworx-poc
  labels:
    app: encrypted-pvc-pod
spec:
  selector:
    matchLabels:
      app: encrypted-pvc-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: encrypted-pvc-pod
    spec:
      schedulerName: stork
      containers:
      - name: nginx-unprivileged
        image: nginxinc/nginx-unprivileged
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/var/www/html"
          name: nginx-encrypted-pvc
      volumes:
      - name: nginx-encrypted-pvc
        persistentVolumeClaim:
          claimName: nginx-encrypted-pvc
