apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: nginx-pvc-ha
  namespace: portworx-poc
  labels:
    app: nginx-pvc-ha
spec:
  selector:
    matchLabels:
      app: nginx-pvc-ha
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-pvc-ha
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - px-demo
            topologyKey: "kubernetes.io/hostname"
      schedulerName: stork
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: "/var/www/html"
            name: nginx-pvc
        resources: {}
      volumes:
      - name: nginx-pvc
        persistentVolumeClaim:
          claimName: nginx-pvc-ha
