apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationRestore
metadata:
  name: wordpress-app-restore
  namespace: wordpress
spec:
  backupName: wordpress-app-backup
  backupLocation: wordpress-backup
  namespaceMapping:
    wordpress: wordpress
  replacePolicy: Delete
  