apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackup
metadata:
  name: wordpress-app-backup
  namespace: wordpress
spec:
  backupLocation: wordpress-backup
  namespaces:
  - wordpress
  reclaimPolicy: Delete
  