apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
  name: wordpress-backup
  namespace: wordpress
  annotations:
    stork.libopenstorage.org/skipresource: "true"
location:
  type: s3
  path: "name-of-your-s3"
  secretConfig: s3secret
  sync: true