apiVersion: v1
kind: Secret
metadata:
  name: s3secret
  namespace: wordpress
  annotations:
    stork.libopenstorage.org/skipresource: "true"
type: Opaque
data:
  accessKeyID: "QUtJQVczTUVBSEZKTVBIMkpDTjcK"
  secretAccessKey: "REJmTDRBclRXbVdMMzlrQkhPcE5jNDd3bVJhNy8ybG1DZElRZzU0WAo="
  region: "ZXUtd2VzdC0xCg=="
  endpoint: "czMuYW1hem9uYXdzLmNvbQo="
  disableSSL: "ZmFsc2UK"

  # accessKeyID: "AKIAW3MEAHFJMPH2JCN7"
  # secretAccessKey: "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"
  # region: "eu-west-1"
  # endpoint: "s3.amazonaws.com"
  # disableSSL: "false"
