apiVersion: v1
kind: Secret
metadata:
  name: s3secret
  namespace: wordpress
  annotations:
    stork.libopenstorage.org/skipresource: "true"
type: Opaque
data:
  accessKeyID: "your-access-id-in-base64" # accessKeyID in base64
  secretAccessKey: "your-secret-access-key-in-base64" # secretAccessKey in base64
  region: "your-region-in-base64" # eu-west-1 in base64
  endpoint: "czMuYW1hem9uYXdzLmNvbQo=" # s3.amazonaws.com in base64 - leave this value
  disableSSL: "ZmFsc2UK" # false in base64 - leave this value